# Generated by Django 2.0.6 on 2018-06-28 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180626_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroclass',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['-name']},
        ),
    ]
