# Generated by Django 2.0.6 on 2018-07-07 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_actor_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Campaign'),
        ),
        migrations.AddField(
            model_name='group',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Campaign'),
        ),
        migrations.AddField(
            model_name='grouptype',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Campaign'),
        ),
        migrations.AddField(
            model_name='heroclass',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Campaign'),
        ),
        migrations.AddField(
            model_name='item',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Campaign'),
        ),
        migrations.AddField(
            model_name='itemproperty',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Campaign'),
        ),
        migrations.AddField(
            model_name='location',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Campaign'),
        ),
        migrations.AddField(
            model_name='locationtype',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Campaign'),
        ),
        migrations.AddField(
            model_name='race',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Campaign'),
        ),
    ]
