# Generated by Django 2.0.6 on 2018-06-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180628_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
