# Generated by Django 2.0.6 on 2018-07-07 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180707_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Campaign')),
                ('events', models.ManyToManyField(to='main.Event')),
                ('givers', models.ManyToManyField(related_name='givers', to='main.Actor')),
                ('locations', models.ManyToManyField(to='main.Location')),
                ('participants', models.ManyToManyField(related_name='participants', to='main.Actor')),
                ('requisites', models.ManyToManyField(to='main.Quest')),
                ('reward', models.ManyToManyField(to='main.Item')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
