# Generated by Django 2.0.6 on 2018-07-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180707_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='events',
            field=models.ManyToManyField(blank=True, to='main.Event'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='givers',
            field=models.ManyToManyField(blank=True, related_name='givers', to='main.Actor'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='locations',
            field=models.ManyToManyField(blank=True, to='main.Location'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to='main.Actor'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='requisites',
            field=models.ManyToManyField(blank=True, to='main.Quest'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='reward',
            field=models.ManyToManyField(blank=True, to='main.Item'),
        ),
    ]
