# Generated by Django 2.0.6 on 2018-06-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180628_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='locations',
            field=models.ManyToManyField(blank=True, to='main.Location'),
        ),
    ]
