# Generated by Django 2.0.6 on 2019-10-02 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180707_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Campaign')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.RemoveField(
            model_name='classprogress',
            name='heroClass',
        ),
        migrations.RemoveField(
            model_name='grouptype',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='heroclass',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='item',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='item',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='itemproperty',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='locationtype',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='race',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='heroClasses',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='race',
        ),
        migrations.RemoveField(
            model_name='group',
            name='type',
        ),
        migrations.RemoveField(
            model_name='location',
            name='type',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='requisites',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='reward',
        ),
        migrations.AlterField(
            model_name='actor',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='surname',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='ClassProgress',
        ),
        migrations.DeleteModel(
            name='GroupType',
        ),
        migrations.DeleteModel(
            name='HeroClass',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemProperty',
        ),
        migrations.DeleteModel(
            name='LocationType',
        ),
        migrations.DeleteModel(
            name='Race',
        ),
        migrations.AddField(
            model_name='object',
            name='currentOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Actor'),
        ),
    ]
