# Generated by Django 2.2.6 on 2019-10-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191001_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='locations',
            field=models.ManyToManyField(blank=True, to='main.Location'),
        ),
    ]
