# Generated by Django 2.0.6 on 2018-07-01 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180629_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('members', models.ManyToManyField(to='main.Actor')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('name', models.TextField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.RemoveField(
            model_name='itemproperty',
            name='id',
        ),
        migrations.RemoveField(
            model_name='itemproperty',
            name='value',
        ),
        migrations.RemoveField(
            model_name='locationtype',
            name='id',
        ),
        migrations.AddField(
            model_name='item',
            name='value',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='itemproperty',
            name='name',
            field=models.TextField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='locationtype',
            name='name',
            field=models.TextField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='group',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.GroupType'),
        ),
    ]
