# Generated by Django 2.0.6 on 2018-07-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180701_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='actors',
            field=models.ManyToManyField(blank=True, to='main.Actor'),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='groups',
            field=models.ManyToManyField(blank=True, to='main.Group'),
        ),
    ]
