# Generated by Django 2.2.6 on 2019-10-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_quest_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='characterClass',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
