# Generated by Django 2.0.6 on 2018-07-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180701_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptype',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemproperty',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationtype',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='name',
            field=models.TextField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='itemproperty',
            name='name',
            field=models.TextField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='locationtype',
            name='name',
            field=models.TextField(max_length=20, unique=True),
        ),
    ]
